### ISSUE TITLE
calculator (+,-,*,/)

### ISSUE THREAD

**Issue by choimingyu99** [opensw-project/python#13]
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y
  
def divide(x, y):
    return x / y

print("연산 종류 선택")
print("1.add")
print("2.sudtract")
print("3.cmultiply")
print("4.divide")

**Comment by kyeong98** [comment]
print("3.cmultiply") 오타있는 것 같습니다

**Comment by K-DongWoo** [comment]
test

**Comment by Yeongjunjeon** [comment]
Good
